name: Create Release on Push to Master

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from AbsentDealer.json
        id: get_version
        run: |
          VERSION=$(jq -r .version AbsentDealer.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create ZIP archive with top-level folder
        run: |
          mkdir absentdealer
          shopt -s dotglob extglob
          # Move all files/folders except .git, .github, and .gitignore
          mv !(absentdealer|.git|.github|.gitignore) absentdealer/
          zip -r absentdealer.zip absentdealer -x 'absentdealer.zip' -x 'absentdealer/.gitignore'

      - name: Generate tag name
        run: echo "RELEASE_TAG=v${{ steps.get_version.outputs.version }}"

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $RELEASE_TAG
          git push origin $RELEASE_TAG
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch all tags
        run: git fetch --tags

      - name: Wait for tag to propagate
        run: sleep 5

      - name: Verify tag exists
        run: git tag -l

      - name: Create GitHub Release using actions/create-release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}
          body: "Release for ${{ env.RELEASE_TAG }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get upload URL
        run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

      - name: Upload ZIP to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./absentdealer.zip
          asset_name: absentdealer.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
