name: Create Release on Push to Master

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZIP archive
        run: |
          zip -r release.zip . -x '*.git*'

      - name: Generate tag name
        run: echo "RELEASE_TAG=v$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # ✅ Create and push Git tag
      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $RELEASE_TAG
          git push origin $RELEASE_TAG
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Fetch all tags to ensure remote tags are available
      - name: Fetch all tags
        run: git fetch --tags

      # ✅ Wait for tag to propagate
      - name: Wait for tag to propagate
        run: sleep 5

      # ✅ Verify release.zip exists
      - name: Verify release.zip exists
        run: ls -l release.zip

      # ✅ Create GitHub Release using the tag
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Upload ZIP to release with explicit path
      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release.zip  # Explicit file path
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
